src/Entity/Person.php
<?php

namespace App\Entity;

use App\Repository\PersonRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Department;
use Doctrine\Common\Collections\Collection;

#[ORM\Entity(repositoryClass: PersonRepository::class)]
class Person
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $last_name = null;

    #[ORM\Column(length: 100)]
    private ?string $first_name = null;

    #[ORM\ManyToOne(targetEntity: User::class, cascade: ["persist"])]
    #[ORM\JoinColumn(nullable: true)]
    private ?User $manager = null;

    #[ORM\ManyToOne(targetEntity: Department::class, cascade: ["persist"])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Department $department = null;

    #[ORM\ManyToOne(targetEntity: Position::class, inversedBy: 'persons', cascade: ["persist"])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Position $position = null;

    #[ORM\OneToOne(mappedBy: 'person', targetEntity: User::class, cascade: ["persist"])]
    private ?User $user = null;

    #[ORM\OneToMany(mappedBy: 'collaborator', targetEntity: Request::class)]
    private Collection $requests;

    public function __construct()
    {
        $this->requests = new ArrayCollection();
    }

    #[ORM\Column]
    private ?bool $alert_new_request = null;

    #[ORM\Column]
    private ?bool $alert_on_answer = null;

    #[ORM\Column]
    private ?bool $alert_before_vacation = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getManagerId(): ?User
    {
        return $this->manager;
    }

    public function setManager(?User $manager): static
    {
        $this->manager = $manager;

        return $this;
    }

    public function getDepartment(): ?Department
    {
        return $this->department;
    }

    public function getDepartmentId(): ?int
    {
        return $this->department ? $this->department->getId() : null;
    }

    public function setDepartment(?Department $department): static
    {
        $this->department = $department;

        return $this;
    }

    public function getPositionId(): ?Position
    {
        return $this->position;
    }

    public function setPosition(?Position $position): static
    {
        $this->position = $position;

        return $this;
    }

    public function isAlertNewRequest(): ?bool
    {
        return $this->alert_new_request;
    }

    public function setAlertNewRequest(bool $alert_new_request): static
    {
        $this->alert_new_request = $alert_new_request;

        return $this;
    }

    public function isAlertOnAnswer(): ?bool
    {
        return $this->alert_on_answer;
    }

    public function setAlertOnAnswer(bool $alert_on_answer): static
    {
        $this->alert_on_answer = $alert_on_answer;

        return $this;
    }

    public function isAlertBeforeVacation(): ?bool
    {
        return $this->alert_before_vacation;
    }

    public function setAlertBeforeVacation(bool $alert_before_vacation): static
    {
        $this->alert_before_vacation = $alert_before_vacation;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;
        return $this;
    }

    public function getFirstNameLastName(): string
    {
        return $this->first_name . " " . $this->last_name;
    }

    //METHODE POUR RECUPERER LES CONGES
    public function getRequests(): Collection
    {
        return $this->requests;
    }

    //FONCTION QUI CALCULE LES JOURS RESTANTS
    public function getTotalLeaveDays(): int
    {
        $totalDays = 0;

        foreach ($this->requests as $request) {
            if ($request->getStartAt() && $request->getEndAt()) {
                $startDate = $request->getStartAt();
                $endDate = $request->getEndAt();
                $currentDate = clone $startDate;

                // Calculer le nombre total de jours en excluant les weekends
                while ($currentDate <= $endDate) {
                    // Si le jour est un samedi (6) ou un dimanche (0), ne pas l'ajouter
                    if ($currentDate->format('N') < 6) {
                        $totalDays++;
                    }

                    $currentDate->modify('+1 day');
                }
            }
        }

        return $totalDays;
    }

    public function getRoles(): array
    {
        return $this->user ? $this->user->getRoles() : [];
    }
}

src/Entity/Request.php
<?php

namespace App\Entity;

use App\Repository\RequestRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\RequestType; 
use App\Entity\Person; 
use App\Entity\Department; 

#[ORM\Entity(repositoryClass: RequestRepository::class)]
class Request
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: RequestType::class, inversedBy: 'requests', cascade: ["persist"])]
    #[ORM\JoinColumn(nullable: false)]
    private ?RequestType $request_type;

    #[ORM\ManyToOne(targetEntity: Person::class, inversedBy: 'requests')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Person $collaborator = null;

    #[ORM\ManyToOne(targetEntity: Department::class)]
    #[ORM\JoinColumn(nullable: false)]
    private ?Department $department = null;

    #[ORM\Column]
    private ?\DateTime $created_at = null;
    public function __construct()
    {
        $this->created_at = new \DateTime();
    }

    #[ORM\Column]
    private ?\DateTime $start_at = null;

    #[ORM\Column]
    private ?\DateTime $end_at = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $receipt_file = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $comment = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $answer_comment = null;

    #[ORM\Column(nullable: true)]
    private ?bool $answer = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTime $answer_at = null;

    public ?int $totalnbdemande = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRequestType(): ?RequestType
    {
        return $this->request_type;
    }

    public function setRequestType(?RequestType $request_type): self
    {
        $this->request_type = $request_type;
        return $this;
    }

    public function getCollaborator(): ?Person
    {
        return $this->collaborator;
    }

    public function setCollaborator(?Person $collaborator): self
    {
        $this->collaborator = $collaborator;
        return $this;
    }

    public function getDepartment(): ?Department
    {
        return $this->department;
    }

    public function setDepartment(?Department $department): self
    {
        $this->department = $department;
        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAtValue(): void
{
    if ($this->created_at === null) {
        $this->created_at = new \DateTime();
    }
}

    public function getStartAt(): ?\DateTime
    {
        return $this->start_at;
    }

    public function setStartAt(?\DateTime $start_at): static
    {
        $this->start_at = $start_at;

        return $this;
    }

    public function getEndAt(): ?\DateTime
    {
        return $this->end_at;
    }

    public function setEndAt(?\DateTime $end_at): static
    {
        $this->end_at = $end_at;

        return $this;
    }

    public function getReceiptFile(): ?string
    {
        return $this->receipt_file;
    }

    public function setReceiptFile(?string $receipt_file): static
    {
        $this->receipt_file = $receipt_file;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): static
    {
        $this->comment = $comment;

        return $this;
    }

    public function getAnswerComment(): ?string
    {
        return $this->answer_comment;
    }

    public function setAnswerComment(?string $answer_comment): static
    {
        $this->answer_comment = $answer_comment;

        return $this;
    }

    public function isAnswer(): ?bool
    {
        return $this->answer;
    }

    public function setAnswer(?bool $answer): static
    {
        $this->answer = $answer;

        return $this;
    }

    public function getAnswerAt(): ?\DateTime
    {
        return $this->answer_at;
    }

    public function setAnswerAt(\DateTime $answer_at): static
    {
        $this->answer_at = $answer_at;

        return $this;
    }

    public function getTotalNbDemande(): int
    {
        // Logique pour calculer totalnbdemande
        return $this->totalnbdemande; // ou la valeur calculée
    }


    //FONCTION QUI CALCULE LE NOMBRE DE JOURS
    public function getNbDays(): int
    {
        if (!$this->start_at || !$this->end_at) {
            return 0;
        }

        $startDate = clone $this->start_at;
        $endDate = clone $this->end_at;
        $workingDays = 0;

        while ($startDate <= $endDate) {
            // format('N') renvoie 1 (lundi) à 7 (dimanche)
            if ((int)$startDate->format('N') < 6) {
                $workingDays++;
            }
            $startDate->modify('+1 day');
        }

        return $workingDays;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'Il existe déjà un compte avec cet email.')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = ['ROLE_COLLABORATEUR'];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column]
    private ?bool $enabled = null;

    #[ORM\OneToOne(inversedBy: 'user', targetEntity: Person::class)]
    #[ORM\JoinColumn(nullable: false)]
    private Person $person;

    #[ORM\Column]
    private ?DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private bool $isVerified = false;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_COLLABORATEUR';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function isEnabled(): ?bool
    {
        return $this->enabled;
    }

    public function setEnabled(bool $enabled): static
    {
        $this->enabled = $enabled;
        return $this;
    }

    public function getCreatedAt(): ?DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getPerson(): ?Person
    {
        return $this->person;
    }

    public function setPerson(Person $person): static
    {
        $this->person = $person;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function __construct()
    {
        $this->created_at = new DateTimeImmutable(); 
    }

    public function getFirstNameLastName(): string
    {
        return $this->person->getFirstNameLastName();
    }
}

src/Controller/Manager/PreferenceController.php
<?php

namespace App\Controller\Manager;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Form\PreferenceManagerType;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\User;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\Security\Http\Attribute\IsGranted;

class PreferenceController extends AbstractController
{
    //PAGE DES PREFERENCES POUR LE MANAGER
    #[IsGranted('ROLE_MANAGER')]
    #[Route('/preference-manager', name: 'app_preference_manager')]
    public function viewPreferenceManager(EntityManagerInterface $entityManager, Request $request, Security $security): Response
    {
        // Récupérer l'utilisateur connecté
        $user = $security->getUser();
        if (!$user instanceof User) {
            throw new \LogicException("Ce n'est pas un type user."); 
            // Dans certains cas, elle peut aussi retourner un autre type d'objet (comme une UserInterface générique).
            // Cette vérification évite d'accéder à la méthode getId() sur un objet qui ne serait pas un User (et donc éviter une erreur fatale).
        }

        // Récupérer l'entité Person associée
        $person = $user->getPerson();
        if (!$person) {
            throw $this->createNotFoundException('Aucune donnée personnelle trouvée pour cet utilisateur.');
        }

        // Créer le formulaire
        $form = $this->createForm(PreferenceManagerType::class, $person);
        $form->handleRequest($request);

        // Traiter le formulaire
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($person);
            $entityManager->flush();

            $this->addFlash('success', 'Vos préférences ont été mises à jour.');
        }

        // Rendre la vue
        return $this->render('manager/preference.html.twig', [
            'form' => $form->createView(),
            'page' => 'preference-manager',
        ]);
    }
}

templates/manager/detail_history_request.html.twig
{# templates/Manager/detail_request_pending.html.twig #}

{% extends 'base.html.twig' %}

{% block body %}

	<title>
		{% block title %}Manager - Consulter une demande{% endblock %}
	</title>

	{% include 'layout/menu/_header.html.twig' %}

	<main style="display: flex;">

		{% include 'layout/menu/_sidebar.html.twig' %}

		<div class="w-full p-8 overflow-y-auto">

			<h1 class="text-left font-bold text-2xl mb-4 " style='color : #004C6C'>Demande de
				{{ request.collaborator.firstname }}
				{{ request.collaborator.lastname }}</h1>
			<h2 class="text-left font-semibold text-m mb-4" style='color : #38738c'>Demande du
				{{ request.createdAt|date('d/m/Y H:i') }}</h2>

			<p class="my-2">Période :
				{{ request.startAt|date('d/m/Y') }}
				au
				{{ request.endAt|date('d/m/Y') }}</p>
			<p class="my-2">Type de demande :
				{{ request.requestType.name }}</p>
			<p class="my-2">Nombre de jours :
				{{ request.collaborator.totalLeaveDays }}
				{% if request.collaborator.totalLeaveDays <= 1 %}
					jour
				{% else %}
					jours
				{% endif %}
			</p>

			<p class="mb-2 mt-5">Commentaire supplémentaire</p>
			<textarea id="" class="w-[55%] h-[25%] bg-white border border-[#dfe4ea] rounded-md p-5 resize-none font-[5]" readonly>{{ request.comment }}</textarea>

			{% if request.receiptFile %}
				<a href="{{ asset('assets/uploads/' ~ request.receiptFile) }}" download class="text-[#004c6c] bg-[#ebf1f4] border-none rounded-md w-[300px] h-[35px] font-medium my-7 cursor-pointer block text-center flex items-center justify-center">
					Télécharger le justificatif
				</a>
			{% else %}
				<p class="text-[#004c6c] bg-[#ebf1f4] border-none rounded-md w-[300px] h-[35px] font-medium my-7 cursor-pointer block text-center flex items-center justify-center">
					Aucun justificatif
				</p>
			{% endif %}
		</div>
	</main>
{% endblock %}

templates/manager/detail_request_pending.html.twig
{# templates/Manager/detail_request_pending.html.twig #}

{% extends 'base.html.twig' %}

{% block body %}

	<title>
		{% block title %}Manager - Consulter une demande
		{% endblock %}
	</title>

	{% include 'layout/menu/_header.html.twig' %}

	<main style="display: flex;">
		{% include 'layout/menu/_sidebar.html.twig' %}
	
		<div class="w-full p-8 overflow-y-hidden">

			<h1 class="text-left font-bold text-2xl mb-4 " style='color : #004C6C'>Demande de
				{{ request.collaborator.firstname }}
				{{ request.collaborator.lastname }}</h1>
			<h2 class="text-left font-semibold text-m mb-4" style='color : #38738c'>Demande du
				{{ request.createdAt|date('d/m/Y H:i') }}</h2>

			<p class="my-2">Période :
				{{ request.startAt|date('d/m/Y H:i') }}
				au
				{{ request.endAt|date('d/m/Y H:i') }}</p>
			<p class="my-2">Type de demande :
				{{ request.requestType.name }}</p>
			<p class="my-2">Nombre de jours :
				{{ nbDaysWorking }}
				{% if nbDaysWorking <= 1 %}
					jour
				{% else %}
					jours
				{% endif %}
			</p>

			<p class="mb-2 mt-5">Commentaire supplémentaire</p>
			<textarea id="" class="w-[50%] h-[10%] bg-white border border-[#dfe4ea] rounded-md p-5 resize-none font-[5]" readonly>{{ request.comment }}</textarea>

			{% if request.receiptFile %}
				<a href="{{ asset('assets/uploads/' ~ request.receiptFile) }}" download class="text-[#004c6c] bg-[#ebf1f4] border-none rounded-md w-[300px] h-[35px] font-medium my-7 cursor-pointer block text-center flex items-center justify-center">
					Télécharger le justificatif
				</a>
			{% else %}
				<p class="text-[#004c6c] bg-[#ebf1f4] border-none rounded-md w-[300px] h-[35px] font-medium my-7 cursor-pointer block text-center flex items-center justify-center">
					Aucun justificatif
				</p>
			{% endif %}

			<h1 class="text-left font-bold text-2xl mb-4 " style='color : #004C6C'>Répondre à la demande</h1>
			{{ form_start(form) }}
            <div>
			{{ form_row(form.answer) }}
            </div>
            <div class="flex space-x-4">
                <div class="w-1/4">
				<input type="hidden" name="id" value="{{ requestId }}">
                    {{ form_row(form.refuse, {'attr': {'class': 'w-full text-white bg-red-500 hover:bg-red-600 border-none rounded-md h-[35px] font-medium cursor-pointer'}}) }}
                </div>
                <div class="w-1/4">
                    {{ form_row(form.accept, {'attr': {'class': 'w-full text-white bg-green-500 hover:bg-green-600 border-none rounded-md h-[35px] font-medium cursor-pointer'}}) }}
                </div>
            </div>
			{{ form_end(form) }}

		</div>
	</main>
{% endblock %}

templates/manager/history_request.html.twig
{% extends 'base.html.twig' %}

{% block body %}

{% include 'layout/menu/_header.html.twig' %}
	<title>{% block title %}Historique des demandes{% endblock %}</title>
	<main style="display: flex;">
		{% include 'layout/menu/_sidebar.html.twig' %}

		<div class="w-full p-8">
        <h1 class="text-left font-bold text-2xl my-4 text-[#004C6C]">Historique des demandes</h1>
            <table class="text-gray-600 min-w-full border-collapse border border-gray-200 shadow-sm rounded-lg">
                <thead class="bg-gray-100 text-gray-700">
                    {{ form_start(form) }}
                        <tr class="bg-[#F9FAFB] text-gray-700 border-x border-t border-[#EAECF0] rounded-lg">
                            <td class="py-4 px-6 pr-0 w-1/6">
                                {{ form_label(form.request_type, null, {'label_attr': {'class': 'block text-sm font-bold mb-2 flex items-center justify-start'}}) }}
                                {{ form_widget(form.request_type, {'attr': {'class': 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'}}) }}
                            </td>
                            <td class="py-4 px-6 pr-0 w-1/6">
                                {{ form_label(form.collaborator, null, {'label_attr': {'class': 'block text-sm font-bold mb-2 flex items-center justify-start'}}) }}
                                {{ form_widget(form.collaborator, {'attr': {'class': 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'}}) }}
                            </td>
                            <td class="py-4 px-6 pr-0 w-1/6">
                                {{ form_label(form.start_at, null, {'label_attr': {'class': 'block text-sm font-bold mb-2 flex items-center justify-start'}}) }}
                                {{ form_widget(form.start_at, {'attr': {'class': 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'}}) }}
                            </td>
                                <td class="py-4 px-6 pr-0 w-1/6">
                                {{ form_label(form.end_at, null, {'label_attr': {'class': 'block text-sm font-bold mb-2 flex items-center justify-start'}}) }}
                                {{ form_widget(form.end_at, {'attr': {'class': 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'}}) }}
                            </td>
                            <td class="py-4 px-4 pr-0 w-1/6">
                                {{ form_label(form.totalnbdemande, null, {'label_attr': {'class': 'block text-sm font-bold mb-2 flex items-center justify-start'}}) }}
                                {{ form_widget(form.totalnbdemande, {'attr': {'class': 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'}}) }}
                            </td>
                             <td class="py-2 px-3 pr-0 w-1/4">
                                {{ form_label(form.answer, null, {'label_attr': {'class': 'block text-sm font-bold mb-2 flex items-center justify-start'}}) }}
                                {{ form_widget(form.answer, {'attr': {'class': 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'}}) }}
                            </td>
                            <td class="w-1/6 px-6 pr-6" colspan="3" style="vertical-align: bottom; padding-bottom: 15px;">
                                <div>
                                    {{ form_widget(form.submit, {'attr': {'class': 'bg-[#004c6c] hover:bg-blue-700 text-white font-bold rounded py-2 px-6'}}) }}
                                </div>
                            </td>
                        </tr>
                    {{ form_end(form) }}
                </thead>
                <tbody>
                   {% for request in requests %} 
                        <tr class="border-t border-b"> 
                            <td class="px-4 py-6">{{ request.requestType.name }}</td>
                            <td class="px-4 py-6 border-t border-b border-gray-300">{{ request.collaborator.firstName }} {{ request.collaborator.lastName}}</td>
                            <td class="px-4 py-6 border-t border-b border-gray-300">{{ request.startAt|date('d/m/Y H:i') }}</td>
                            <td class="px-4 py-6 border-t border-b border-gray-300">{{ request.endAt|date('d/m/Y H:i') }}</td>
                            <td class="px-4 py-6 border-t border-b border-gray-300">
                                {% set date1 = request.startAt|date('U') %}
                                {% set date2 = request.endAt|date('U') %}
                                
                                {% set diff = (date2 - date1) / 86400 %}
                                {{ diff }} jours
                            </td>

                            <td class="px-4 py-6 border-t border-b border-gray-300">
                                <div class="{% if request.answer is null %}{% elseif request.answer == 1 %}{% else %}{% endif %}">
                                    {% if request.answer is null %}
                                        En attente
                                    {% elseif request.answer == true %}
                                        Validé
                                    {% elseif request.answer == false %}
                                        Refusé
                                    {% endif %}
                                </div>
                            </td>
                            <td class="py-6 px-6">
                                <form method="POST" action="{{ path('app_detail_history_request', {'id': request.id}) }}">
                                    <button type="submit" class="bg-gray-200 px-3 py-1 rounded">Détails</button>
                                </form>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="7" class="px-4 py-2 text-center text-gray-500">Aucune demande trouvée</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="flex w-full justify-center items-center h-max mt-10">
                {% if pager.hasPreviousPage %}
                    <a class="bg-[#004c6c] hover:bg-blue-700 text-white font-bold rounded py-2 px-6 m-4" href="{{ path('app_history_request_manager', { page: pager.previousPage }) }}">Précédent</a>
                {% endif %}
                    <p>Page {{ pager.currentPage }} sur {{ pager.nbPages }}</p>
                {% if pager.hasNextPage %}
                    <a class="bg-[#004c6c] hover:bg-blue-700 text-white font-bold rounded py-2 px-6 m-4" href="{{ path('app_history_request_manager', { page: pager.nextPage }) }}">Suivant</a>
                {% endif %}
            </div>
        </div>
    </main>
{% endblock %}

templates/manager/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    {% include 'layout/manager/_sidebar.html.twig' %}
{% endblock %}

templates/manager/preference.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {% if is_granted('ROLE_MANAGER') %}
        <title>{% block title %}Manager - Mes préférences{% endblock %}</title>

        {% include 'layout/menu/_header.html.twig' %}

        <main class="flex">

            {% include 'layout/menu/_sidebar.html.twig' %}

            <div class="w-full p-8 overflow-y-auto">

                <h1 class="font-medium text-2xl my-3 text-[#004C6C]">Mes préférences</h1>
                {% include 'layout/_addFlash.html.twig' %}
                {{ form_start(form) }}

                <div class="mt-7 flex items-center">
                    <label class="relative inline-block w-12 h-6">
                        {{ form_widget(form.alert_new_request, { 
                            'attr': { 
                                'class': 'sr-only peer' 
                            } 
                        }) }}
                        <span class="absolute cursor-pointer inset-0 bg-gray-300 rounded-full transition peer-checked:bg-[#004C6C]"></span>
                        <span class="absolute left-1 bottom-1 w-4 h-4 bg-white rounded-full transition peer-checked:translate-x-6"></span>
                    </label>
                    <p class="ml-3 text-sm">Être alerté par email lorsqu'une demande de congé arrive</p>
                </div>

                <div class="mt-7">
                    {{ form_widget(form.submit, { 
                        'attr': { 
                            'class': 'text-white bg-[#004C6C] rounded-lg w-64 h-10 font-medium cursor-pointer hover:bg-[#00334a] transition' 
                        } 
                    }) }}
                </div>

                {{ form_end(form) }}

            </div>
        </main>
    {% else %}
        <p>Vous n'avez pas les permissions nécessaires pour accéder à cette page.</p>
    {% endif %}
{% endblock %}