src/Entity/Request.php
<?php

namespace App\Entity;

use App\Repository\RequestRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\RequestType; 
use App\Entity\Person; 
use App\Entity\Department; 

#[ORM\Entity(repositoryClass: RequestRepository::class)]
class Request
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: RequestType::class, inversedBy: 'requests', cascade: ["persist"])]
    #[ORM\JoinColumn(nullable: false)]
    private ?RequestType $request_type;

    #[ORM\ManyToOne(targetEntity: Person::class, inversedBy: 'requests')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Person $collaborator = null;

    #[ORM\ManyToOne(targetEntity: Department::class)]
    #[ORM\JoinColumn(nullable: false)]
    private ?Department $department = null;

    #[ORM\Column]
    private ?\DateTime $created_at = null;
    public function __construct()
    {
        $this->created_at = new \DateTime();
    }

    #[ORM\Column]
    private ?\DateTime $start_at = null;

    #[ORM\Column]
    private ?\DateTime $end_at = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $receipt_file = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $comment = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $answer_comment = null;

    #[ORM\Column(nullable: true)]
    private ?bool $answer = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTime $answer_at = null;

    public ?int $totalnbdemande = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRequestType(): ?RequestType
    {
        return $this->request_type;
    }

    public function setRequestType(?RequestType $request_type): self
    {
        $this->request_type = $request_type;
        return $this;
    }

    public function getCollaborator(): ?Person
    {
        return $this->collaborator;
    }

    public function setCollaborator(?Person $collaborator): self
    {
        $this->collaborator = $collaborator;
        return $this;
    }

    public function getDepartment(): ?Department
    {
        return $this->department;
    }

    public function setDepartment(?Department $department): self
    {
        $this->department = $department;
        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAtValue(): void
{
    if ($this->created_at === null) {
        $this->created_at = new \DateTime();
    }
}

    public function getStartAt(): ?\DateTime
    {
        return $this->start_at;
    }

    public function setStartAt(?\DateTime $start_at): static
    {
        $this->start_at = $start_at;

        return $this;
    }

    public function getEndAt(): ?\DateTime
    {
        return $this->end_at;
    }

    public function setEndAt(?\DateTime $end_at): static
    {
        $this->end_at = $end_at;

        return $this;
    }

    public function getReceiptFile(): ?string
    {
        return $this->receipt_file;
    }

    public function setReceiptFile(?string $receipt_file): static
    {
        $this->receipt_file = $receipt_file;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): static
    {
        $this->comment = $comment;

        return $this;
    }

    public function getAnswerComment(): ?string
    {
        return $this->answer_comment;
    }

    public function setAnswerComment(?string $answer_comment): static
    {
        $this->answer_comment = $answer_comment;

        return $this;
    }

    public function isAnswer(): ?bool
    {
        return $this->answer;
    }

    public function setAnswer(?bool $answer): static
    {
        $this->answer = $answer;

        return $this;
    }

    public function getAnswerAt(): ?\DateTime
    {
        return $this->answer_at;
    }

    public function setAnswerAt(\DateTime $answer_at): static
    {
        $this->answer_at = $answer_at;

        return $this;
    }

    public function getTotalNbDemande(): int
    {
        // Logique pour calculer totalnbdemande
        return $this->totalnbdemande; // ou la valeur calculée
    }


    //FONCTION QUI CALCULE LE NOMBRE DE JOURS
    public function getNbDays(): int
    {
        if (!$this->start_at || !$this->end_at) {
            return 0;
        }

        $startDate = clone $this->start_at;
        $endDate = clone $this->end_at;
        $workingDays = 0;

        while ($startDate <= $endDate) {
            // format('N') renvoie 1 (lundi) à 7 (dimanche)
            if ((int)$startDate->format('N') < 6) {
                $workingDays++;
            }
            $startDate->modify('+1 day');
        }

        return $workingDays;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'Il existe déjà un compte avec cet email.')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = ['ROLE_COLLABORATEUR'];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column]
    private ?bool $enabled = null;

    #[ORM\OneToOne(inversedBy: 'user', targetEntity: Person::class)]
    #[ORM\JoinColumn(nullable: false)]
    private Person $person;

    #[ORM\Column]
    private ?DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private bool $isVerified = false;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_COLLABORATEUR';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function isEnabled(): ?bool
    {
        return $this->enabled;
    }

    public function setEnabled(bool $enabled): static
    {
        $this->enabled = $enabled;
        return $this;
    }

    public function getCreatedAt(): ?DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getPerson(): ?Person
    {
        return $this->person;
    }

    public function setPerson(Person $person): static
    {
        $this->person = $person;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function __construct()
    {
        $this->created_at = new DateTimeImmutable(); 
    }

    public function getFirstNameLastName(): string
    {
        return $this->person->getFirstNameLastName();
    }
}

src/Controller/collaborator/InformationController.php
<?php

namespace App\Controller\collaborator;

use App\Entity\Person;
use App\Entity\User;
use App\Form\MotDePasseType;
use App\Form\InformationFormType;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\SecurityBundle\Security; 
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Security\Http\Attribute\IsGranted;

class InformationController extends AbstractController

{
    public function __construct(private UserPasswordHasherInterface $passwordHasher){
        
    }
    //PAGE INFORMATIONS "COLLABORATEUR"
    #[IsGranted('ROLE_COLLABORATEUR')]
    #[Route('/information-collaborateur', name: 'app_information_collaborateur')]
    public function viewInformationCollaborateur(ManagerRegistry $registry, Security $security, Request $request,UserPasswordHasherInterface $hash,EntityManagerInterface $entityManager): Response
    {
        $person = new Person();
        $user = new User() ;
        $collaborator = New User() ; 
        $collaborator = $security->getUser() ;
        if (!$collaborator instanceof \App\Entity\User) {
            throw new \LogicException('L\'utilisateur connecté n\'est pas une instance de App\Entity\User.');
        }
        $person  = $collaborator->getPerson();
        $form_person= $this->createForm(InformationFormType::class, $person);
        $form_password = $this->createForm(MotDePasseType::class, $user);
        $form_password->handleRequest($request);
        
        if ($form_password->isSubmitted()){
            if($form_password->isValid()) {
                $data = $form_password->getData() ; 
                // $currentPassword = $data['currentPassword'] ;                 
                // $newPassword = $data['newPassword'] ; 
                // $confirmPassword = $data['confirmPassword'] ; 
                $currentPassword = $form_password->get('currentPassword')->getData();
                $newPassword = $form_password->get('newPassword')->getData();
                $confirmPassword = $form_password->get('confirmPassword')->getData();

                $verifHash = $this->passwordHasher->hashPassword($user, $currentPassword) ;
                if ($hash->isPasswordValid($collaborator, $currentPassword)) {
                    if($newPassword != $currentPassword){
                        if($newPassword == $confirmPassword){
                            if($newPassword || $confirmPassword != $currentPassword){
                                $password = $this->passwordHasher->hashPassword($user, $newPassword) ; 
                                $collaborator->setPassword($password) ; 
                                $entityManager->flush(); // Mettre à jour l'entité

                                $this->addFlash('success', 'Mot de passe modifié'); //Création d'un message flash de succès
                            }else{
                                $this->addFlash('error', 'Le nouveau mot passe est le même que l\'actuel');
                            }
                        }else{
                            $this->addFlash('error', 'La confirmation du nouveau mot de passe ne correspond pas au nouveau mot de passe');
                        }   
                    }else{
                        $this->addFlash('error', 'Le nouveau mot de passe est identique à l\'actuel');
                    }
                }else{
                    $this->addFlash('error', 'Le mot de passe actuel est incorrect'); //Création d'un message flash erreur 
                }
            }
        }

        return $this->render('collaborator/information.html.twig', [
            'page' => 'information-collaborator',
            'form1' => $form_person,
            'form2' => $form_password, 
        ]);
    }
}

src/Controller/collaborator/PreferenceController.php
<?php

namespace App\Controller\collaborator;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Repository\PersonRepository; 
use App\Form\PreferenceType; 
use App\Entity\User;
use Doctrine\Persistence\ManagerRegistry;
use App\Service\MailerService;
use Symfony\Component\Security\Http\Attribute\IsGranted;

class PreferenceController extends AbstractController
{
    //PAGE PREFERENCE "COLLABORATEUR"
    #[IsGranted('ROLE_COLLABORATEUR')]
    #[Route('/preference-collaborateur', name: 'app_preference_collaborateur')]
    public function viewPreferenceCollaborateur(ManagerRegistry $registry, PersonRepository $repository, Request $request, MailerService $mailer ): Response
    {
        /** @var User $user */ 
        $user = $this->getUser() ; //récupère l'objet de l'utilisateur connecté  
        $userHost = $user->getPerson() ; 
        $id = $userHost->getId();
        
        $person = $repository->find($id) ; 
        if(!$person){
            throw $this->createNotFoundException('No person found for id ' . $id);
        }
        $form = $this->createForm(PreferenceType::class, $person ) ; 
        $form->handleRequest($request) ; 

        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                // Si valide : j'enregistre les données dans la BDD.
                $request->cookies->all();
                $registry->getManager()->flush();
                $this->addFlash('success','Modifications de préférences enregistées');
                // Faire une redirection vers le formulaire de modification.
            } else {
                // Sinon j'affiche un message d'erreur
                $this->addFlash('error','Erreur lors des modifications de préférences enregistées');
            }
        }

        return $this->render('collaborator/preference.html.twig', [
            'page' => 'preference-collaborateur',
            'form' => $form , 
        ]);
    }
}

templates/collaborator/detail_request.html.twig
{# templates/collaborateur/detail_request.html.twig #}

{% extends 'base.html.twig' %}

{% block body %}

	<title>
		{% block title %}Détails d'une Demande
		{% endblock %}
	</title>

	{% include 'layout/menu/_header.html.twig' %}

	<main style="display: flex;">

		{% include 'layout/menu/_sidebar.html.twig' %}

		<div class="w-full p-8 overflow-y-auto">
			<h1 class="text-left font-bold text-2xl my-4 " style='color : #004C6C'>Ma demande de congé</h1>
			<h2 class="text-left font-semibold text-m mb-4" style='color : #38738c'>Demande du
				{{ request.createdAt|date('d/m/Y H:i') }}</h2>

			<p class="my-2">Type de demande :
				{{ request.requestType.name }}</p>
			<p class="my-2">Période :
				{{ request.startAt|date('d/m/Y') }}
				au
				{{ request.endAt|date('d/m/Y') }}</p>
			<p class="my-2">Nombre de jours : {{ request.nbdays }} jours ouvrés.</p>

			<p class="my-[30px]">Statut de la demande :
				<span class="text-[#329159] bg-[#daf8e6] px-2 py-0 rounded-full ml-1 font-medium">
					{% if request.answer is null %}
						En attente
					{% elseif request.answer == true %}
						Validé
					{% elseif request.answer == false %}
						Refusé
					{% endif %}
				</span>
			</p>

			<p class="my-2">Commentaire du manager :</p>
			<textarea id="" class="w-[55%] h-[25%] text-[#b4c4cf] bg-white border border-[#dfe4ea] rounded-md p-5 resize-none" readonly>{{ request.answerComment }}</textarea>

			<a type="submit" href="{{ path('app_request_history_collaborator') }}" class="text-[#004c6c] bg-[#ebf1f4] border-none rounded-md w-[300px] h-[35px] font-medium my-7 cursor-pointer block text-center flex items-center justify-center">Retourner à la liste de mes demandes</a>
		</div>
	</main>

{% endblock %}

templates/collaborator/information.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<title>{% block title %}Mes informations{% endblock %}</title>

	<script src="{{ asset('assets/js/ViewPasswordCollaborateur.js') }}"></script>
	{% include 'layout/menu/_header.html.twig' %}
	
	<main style="display: flex;">
		{% include 'layout/menu/_sidebar.html.twig' %}
		<div class="w-full p-8">
         <h1 class="text-left font-bold text-2xl my-4 text-[#004C6C]">Mes informations</h1>
            {{ form_start(form1) }}
                <div class="space-y-6">
                    <div class="grid grid-cols-2 gap-4">
                        <div>
                            {{ form_row(form1.last_name) }}
                        </div>
                        <div>
                            {{ form_row(form1.first_name) }}
                        </div>
                    </div>
                    <div class="grid grid-cols-2 gap-4">
                        <div class="col-span-1">
                            {{ form_row(form1.email) }}
                        </div>
                    </div>
                    <div class="grid grid-cols-2 gap-4">
                        <div class="col-span-1">
                            {{ form_row(form1.department)}}
                        </div>
                        <div class="col-span-1">
                            {{ form_row(form1.position_id)}}
                        </div>
                    </div>
                    <div class="grid grid-cols-2 gap-4">
                        <div class="col-span-1">
                            {{ form_row(form1.manager_id) }}
                        </div>
                    </div>
                </div>
            {{ form_end(form1) }}

            <h2 class="text-xl font-semibold text-gray-900 mt-8 mb-4">Réinitialiser mon mot de passe</h2>
            {% include 'layout/_addFlash.html.twig'%} {# include pour appeler le message flash dans le formulaire#}
                <form method="post">
                <div class="space-y-6">
                {{ form_start(form2) }}
                    <div class="grid grid-cols-1">
                        <div class="w-1/2">
                            <label class="block font-medium">{{ form_label(form2.currentPassword) }}</label>
                            <div class="relative">
                                {{ form_widget(form2.currentPassword, { attr: { id: 'password', class: "w-full mt-1 p-2 border border-gray-300 rounded-md pr-10" } }) }}
                                <button type="button" id="togglePassword" class="absolute inset-y-0 right-0 flex items-center pr-3 mt-1">
                                    <img id="eyeIcon" src="{{ asset('assets/image/eye-slash-solid.svg') }}" data-eye-open="{{ asset('assets/image/eye-solid.svg') }}" 
                                    data-eye-closed="{{ asset('assets/image/eye-slash-solid.svg') }}" alt="Afficher/Masquer" class="w-5 h-5">
                                </button>
                            </div>
                            <h3 class="text-red-500 mt-1">{{ form_errors(form2.currentPassword) }}</h3>
                        </div>
                        <br>
                        <div class="grid grid-cols-2 gap-x-1 gap-y-1">
                            <div class ="w-full">
                                <label class="block font-medium">{{ form_label(form2.newPassword) }}</label>
                                <div class="relative">
                                    {{ form_widget(form2.newPassword, { attr: { class: "w-full mt-1 p-2 border border-gray-300 rounded-md pr-10" } }) }}
                                    <button type="button" id="togglePassword2" class="absolute inset-y-0 right-0 flex items-center pr-3 mt-1">
                                        <img id="eyeIcon" src="{{ asset('assets/image/eye-slash-solid.svg') }}" data-eye-open="{{ asset('assets/image/eye-solid.svg') }}" 
                                        data-eye-closed="{{ asset('assets/image/eye-slash-solid.svg') }}" alt="Afficher/Masquer" class="w-5 h-5">
                                    </button>
                                </div>
                                <h3 class="text-red-500 text-sm mt-1">{{ form_errors(form2.newPassword) }}</h3>
                            </div>
                            <div class ="w-full">
                                <label class="block font-medium">{{ form_label(form2.confirmPassword) }}</label>
                                <div class="relative">
                                    {{ form_widget(form2.confirmPassword, { attr: { class: "w-full mt-1 p-2 border border-gray-300 rounded-md pr-10" } }) }}
                                    <button type="button" id="togglePassword3" class="absolute inset-y-0 right-0 flex items-center pr-3 mt-1">
                                        <img id="eyeIcon" src="{{ asset('assets/image/eye-slash-solid.svg') }}" data-eye-open="{{ asset('assets/image/eye-solid.svg') }}" 
                                        data-eye-closed="{{ asset('assets/image/eye-slash-solid.svg') }}" alt="Afficher/Masquer" class="w-5 h-5">
                                    </button>
                                </div>
                                <h3 class="text-red-500 text-sm mt-1">{{ form_errors(form2.confirmPassword) }}</h3>
                            </div>
                        </div>
                    <div class="mt-6">
                        {{ form_widget(form2.Submit, {'label': 'Réinitialiser le mot de passe', 'attr': {'class': 'bg-[#004c6c] hover:bg-blue-700 text-white rounded py-2 px-6'}}) }}
                    </div>
                </div>
                {{ form_end(form2) }}
                </form>
		</div>
	</main>
{% endblock %}

templates/collaborator/new_request.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<title>{% block title %}Nouvelle demande{% endblock %}</title>
	<script src="{{ asset('assets/js/DayCalculated.js') }}"></script>

	<body>
		{% include 'layout/menu/_header.html.twig' %}

		<main style="display: flex;">
			{% include 'layout/menu/_sidebar.html.twig' %}
			<div class="w-full p-8">
				<h1 class="text-left font-bold text-2xl my-4 text-[#004C6C]">Effectuer une nouvelle demande</h1>
				{% include 'layout/_addFlash.html.twig'%} {# include pour appeler le message flash dans le formulaire#}
				{{ form_start(form, { 'attr': { 'enctype': 'multipart/form-data' } }) }}
					<div class="w-1/2 mb-6">
						<label for="request_type" class="block text-gray-700 text-sm font-bold mb-2">Type de demande - champ obligatoire</label>
						{{ form_widget(form.request_type, {'attr': {'class': 'w-full p-2 border rounded'}}) }}
						{% if form.request_type.vars.errors|length > 0 %}
							<div class="text-red-500 text-sm mt-1">
								{{ form_errors(form.request_type) }}
							</div>
						{% endif %}
					</div>

					<div class="grid grid-cols-2 gap-2">
						<div>
							<label for="start_at" class="block text-gray-700 text-sm font-bold mb-2">Date de début - champ obligatoire</label>
							{{ form_widget(form.start_at, {'attr': { 'class': 'w-full p-2 border rounded', 'oninput': 'calculerJoursOuvres()'}}) }}
							{% if form.start_at.vars.errors|length > 0 %}
								<div class="text-red-500 text-sm mt-1">
									{{ form_errors(form.start_at) }}
								</div>
							{% endif %}
						</div>

						<div>
							<label for="end_at" class="block text-gray-700 text-sm font-bold mb-2">Date de fin - champ obligatoire</label>
							{{ form_widget(form.end_at, {'attr': { 'oninput': 'calculerJoursOuvres()'}}) }}
							{% if form.end_at.vars.errors|length > 0 %}
								<div class="text-red-500 text-sm mt-1">
									{{ form_errors(form.end_at) }}
								</div>
							{% endif %}
						</div>
					</div>

					<div class="w-1/2">
						<label for="working_days" class="block text-gray-700 text-sm font-bold mb-2">Nombre de jours ouvrés</label>
						{{ form_widget(form.working_days, {'attr': { 'readonly': true}}) }}
						{% if form.working_days.vars.errors|length > 0 %}
							<div class="text-red-500 text-sm mt-1">
								{{ form_errors(form.working_days) }}
							</div>
						{% endif %}
					</div>

					<div class="w-1/2 mt-[10px] mb-[10px]">
						<label for="{{ form.receipt_file.vars.id }}" class="block text-gray-700 text-sm font-bold mb-2">
							Justificatif si applicable
						</label>

						{{ form_widget(form.receipt_file, {
							'attr': {
								'class': 'hidden',
							}
						}) }}

						<label for="{{ form.receipt_file.vars.id }}"
							class="flex items-center space-x-2 cursor-pointer w-fit bg-[#ffffff] border border-[#e5e7eb] px-4 py-2 rounded text-gray-700 hover:bg-[#d6e5ed] transition">
							<img src="{{ asset('assets/image/icon-file.png') }}" alt="Upload Icon" class="w-6 h-6">
							<span class="text-sm font-medium">Sélectionner un fichier</span>
						</label>

						{% if form.receipt_file.vars.errors|length > 0 %}
							<div class="text-red-500 text-sm mt-1">
								{{ form_errors(form.receipt_file) }}
							</div>
						{% endif %}
					</div>

					<div class="w-full">
						<label for="comment" class="block text-gray-700 text-sm font-bold mb-2">Commentaire</label>
						{{ form_widget(form.comment) }}
						{% if form.comment.vars.errors|length > 0 %}
							<div class="text-red-500 text-sm mt-1">
								{{ form_errors(form.comment) }}
							</div>
						{% endif %}
					</div>

					<div class="w-1/2">
						{{ form_widget(form.Submit, {'label': 'Soumettre ma demande', 'attr': {'class': 'bg-[#004c6c] hover:bg-blue-700 text-white font-bold rounded py-2 px-6'}}) }}
					</div>
				{{ form_end(form) }}

				<p class="pt-4">*En cas d’erreur de saisie ou de changements, vous pourrez modifier votre demande tant que celle-ci n’a pas été validée par le manager.</p>
			</div>
		</main>
	</body>
{% endblock %}

templates/collaborator/preference.html.twig
{# templates/preference.html.twig #}
{% extends 'base.html.twig' %}

{% block title %}
    Préférences
{% endblock %}

{% block body %}
    {% include 'layout/menu/_header.html.twig' %}
    <main class="flex flex-grow">
        {% include 'layout/menu/_sidebar.html.twig' %}

        <section class="w-full justify-center items-start p-8">
            <div class="bg-white p-6 rounded-lg shadow-md w-full mb-2">
                <h2 class="text-2xl font-bold text-gray-700 mb-6">Mes préférences</h2>
                {% include 'layout/_addFlash.html.twig' %}
                {{ form_start(form) }}
                    <div class="flex-inline flex-grow mb-4">
                        <div class="flex items-center">
                            <label class="relative cursor-pointer">
                            {{ form_widget(form.alert_on_answer, {'attr': {'class': 'hidden peer'}}) }}
                            <div
                                class="w-11 h-6 flex items-center bg-gray-300 rounded-full peer peer-checked:after:translate-x-full after:absolute after:left-[2px] peer-checked:after:border-white after:bg-white after:border after:border-gray-300 after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-[#004C6C]">
                            </div>
                            </label>
                            <label for="{{ form.alert_on_answer.vars.id }}" class="ml-4 text-sm font-medium text-gray-900 dark:text-gray-300">{{ form_label(form.alert_on_answer) }}</label>
                        </div>
                        <div class='mb-4'></div>
                        <div class="flex items-center">
                            <label class="relative cursor-pointer">
                            {{ form_widget(form.alert_before_vacation, {'attr': {'class': 'hidden peer'}}) }}
                            <div
                                class="w-11 h-6 flex items-center bg-gray-300 rounded-full peer peer-checked:after:translate-x-full after:absolute after:left-[2px] peer-checked:after:border-white after:bg-white after:border after:border-gray-300 after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-[#004C6C]">
                            </div>
                            </label>
                            <label for="{{ form.alert_before_vacation.vars.id }}" class="ml-4 text-sm font-medium text-gray-900 dark:text-gray-300">{{ form_label(form.alert_before_vacation, ) }}</label>
                        </div>
                    </div>

                    <div class="flex items-center w-1/4">
                        {{ form_widget(form.submit, ) }}
                    </div>
                {{ form_end(form) }}
            </div>
        </section>
    </main>
{% endblock %}